---
- name: Install the web console (Cockpit) on a system
  hosts: cockpit
  tasks:
    - name: Install the cockpit packages
      yum:
        name: cockpit
        state: latest

    - name: Open the cockpit service/port (tcp/9090) through the firewall
      firewalld:
        service: cockpit
        permanent: true
        immediate: true
        state: enabled

    - name: Start the service/socket
      service:
        name: cockpit.socket
        enabled: true
        state: started
